id: I0751C11D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:46:00+00:00'
last_modified: '2022-06-09T08:06:28.307400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30032
  title: རྨ་ལྷོ་སོག་རྫོང་གི་རྩོམ་རིག་བརྩམས་ཆོས་བདམས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '8944':
      image_group_id: I00EGS1017209
      title: Volume 1 of rma lho sog rdzong gi rtsom rig brtsams chos bdams bsgrigs
      total_pages: 430
      order: 1
      base_file: 8944.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
