id: P007967
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30032
  title: རྨ་ལྷོ་སོག་རྫོང་གི་རྩོམ་རིག་བརྩམས་ཆོས་བདམས་བསྒྲིགས
  author: ''
  volumes:
    8f0f3dddb8ef4281aafcc9949ae86457:
      image_group_id: I00EGS1017209
      title: Volume 1 of rma lho sog rdzong gi rtsom rig brtsams chos bdams bsgrigs
      volume_number: 1
      total_pages: 430
      base_file: v001.txt
