id: P007967
initial_creation_type: ocr
source_metadata:
  id: bdr:W30032
  title: རྨ་ལྷོ་སོག་རྫོང་གི་རྩོམ་རིག་བརྩམས་ཆོས་བདམས་བསྒྲིགས
  author: ''
  volumes:
    4ab08db5c1d042acb9e60d3e00a882c0:
      image_group_id: I00EGS1017209
      title: ''
      volume_number: 1
      total_pages: 430
ebook_metadata:
  title: རྨ་ལྷོ་སོག་རྫོང་གི་རྩོམ་རིག་བརྩམས་ཆོས་བདམས་བསྒྲིགས
  author: ''
  sku: P007967
  cover: cover.jpg
  layers:
  - pagination
